# Generated by Django 3.0.4 on 2020-03-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('amount_of_review', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('product_code', models.IntegerField()),
                ('guarantee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text_spec', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_rev', models.PositiveSmallIntegerField(choices=[(0, 'Star Zero'), (1, 'Star One'), (2, 'Star Two'), (3, 'Star Three'), (4, 'Star Four'), (5, 'Star Five')])),
                ('data', models.DateTimeField(auto_now=True)),
                ('text_rev', models.TextField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(to='main_page.Specification'),
        ),
    ]
