# Generated by Django 3.0.4 on 2020-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charact',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='charact',
            field=models.ManyToManyField(blank=True, to='shop.Charact', verbose_name='Характеристики'),
        ),
    ]
