# Generated by Django 3.0.4 on 2020-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200315_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='mda/', verbose_name='Картинка'),
        ),
    ]
